# This can be used to run a development version of the Angular and Node containers
# Run docker-compose build
# Run docker-compose up

version: "3.7"

services:
  nginx:
    container_name: aws-quiz
    image: aws-quiz
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
    networks:
      - app-network

  node:
    container_name: aws-quiz-server
    image: aws-quiz-server
    build:
      context: ./server
      dockerfile: node.dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    networks:
      - app-network

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
